import type { Product } from "@/lib/types";

export const products: Product[] = [
  {
    id: "aurora-lamp",
    slug: "aurora-lamp",
    name: "Aurora Lamp",
    description: "A sculptural desk lamp with soft ambient lighting for focused evenings.",
    price: 79,
    category: "Home",
    rating: 4.8,
    badge: "Bestseller",
    stock: 12,
    image: "https://images.unsplash.com/photo-1519947486511-46149fa0a254?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "glide-chair",
    slug: "glide-chair",
    name: "Glide Chair",
    description: "Minimal comfort with a supportive silhouette for modern workspaces.",
    price: 149,
    category: "Furniture",
    rating: 4.6,
    badge: "New",
    stock: 8,
    image: "https://images.unsplash.com/photo-1519947486511-46149fa0a254?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "solstice-bag",
    slug: "solstice-bag",
    name: "Solstice Tote",
    description: "Weather-ready carryall made for daily commutes and weekend escapes.",
    price: 64,
    category: "Accessories",
    rating: 4.7,
    badge: "Trending",
    stock: 15,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "nova-speaker",
    slug: "nova-speaker",
    name: "Nova Speaker",
    description: "Immersive sound in a compact design for music lovers at home.",
    price: 129,
    category: "Tech",
    rating: 4.9,
    badge: "Top Rated",
    stock: 5,
    image: "https://images.unsplash.com/photo-1518444065439-e933c06ce9cd?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "harbor-blanket",
    slug: "harbor-blanket",
    name: "Harbor Blanket",
    description: "Ultra-soft knit blanket with a calm texture for cozy downtime.",
    price: 54,
    category: "Home",
    rating: 4.5,
    badge: "Cozy Pick",
    stock: 10,
    image: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "cove-watch",
    slug: "cove-watch",
    name: "Cove Watch",
    description: "A refined everyday watch with a lightweight stainless finish.",
    price: 189,
    category: "Accessories",
    rating: 4.8,
    badge: "Limited",
    stock: 7,
    image: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=800&q=80",
  },
];

export const categories = ["All", ...Array.from(new Set(products.map((product) => product.category)))];
